[package]
name = "gensudoku-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.7"
sudoku-rs = { git = "https://github.com/hwoy/sudoku-rs.git" }

[features]
emsdk=["open64"]
open64=[]
